### ISSUE TITLE
Undefined WebSocketProxyHandler

### ISSUE THREAD

**Issue by betatim** [jupyterhub/nbserverproxy#13]
On this line 

https://github.com/jupyterhub/nbserverproxy/blob/85c963a5e2f85d46396f7a34d9fe2235ce4d4a82/nbserverproxy/handlers.py#L104

the class `WebSocketProxyHandler` is used but it is undefined. Where should it be imported from?

**Comment by yuvipanda** [comment]
Shit lol, how is this even working rn...

**Comment by betatim** [comment]
I think because the code never gets exercised :-/
