### ISSUE TITLE
0.7.1 git tag and PyPI sdist

### ISSUE THREAD

**Issue by jjhelmus** [jupyterhub/nbserverproxy#30]
nbserverproxy 0.7.1 is available as a whl on PyPI.  Would it be possible to tag the release in git and provide a sdist on PyPI?  Both of these would be helpful for downstream distributors of the software.

**Comment by jakirkham** [comment]
There have been a few releases since. Is this still relevant?

**Comment by jjhelmus** [comment]
sdists  have been available on PyPI since 0.8.0, closing.
