### ISSUE TITLE
Proxying Xpra is not working

### ISSUE THREAD

**Issue by BerserkerTroll** [jupyterhub/nbserverproxy#35]
I've tried to proxy [Xpra](https://www.xpra.org/) [html5 client](https://xpra.org/trac/wiki/Clients/HTML5) with `nbserverproxy` (version 0.8.3), but it doesn't seem to work.
When I start Xpra on a local machine with the
```
xpra start --bind-tcp=0.0.0.0:14500 --html=on --start=xterm
```
command and open `localhost:14500`, I see `xterm` in my browser.

I've tried to run this command from the `jupyter` terminal and then access `.../proxy/14500`.
First of all, the HTML page tries to load `js` (or `css`) from `.../proxy/js/` instead of `.../proxy/14500/js`. Ok, I've added a slash to the url and then the page was able to load.

But then, probably because it can't connect to websockets, the [`index.html`](https://github.com/totaam/xpra-html5/blob/master/index.html) page redirects me to [`connect.html`](https://github.com/totaam/xpra-html5/blob/master/connect.html) page, which locally happens only when I stop X server. As I said, this likely means that it has problems with websockets so it thinks that the server is down. **UPD**: In Firefox Network console, the last request from `index.html` page I see is websockets request to the `/`, which is expectedly redirected to `/hub`.

There is Wiki page about proxying Xpra with Nginx: https://www.xpra.org/trac/wiki/Nginx
AFAIU it makes Nginx to do something to HTTP headers so that websockets work behind a proxy.

I know about https://github.com/ryanlovett/nbnovnc/, but I would like to see Xpra working.

**Comment by BerserkerTroll** [comment]
Looks like it is Xpra issue, it doesn't handle websocket paths. Close for now.

**Comment by ryanlovett** [comment]
Hey @BerserkerTroll, thanks for reporting this issue. I think supporting Xpra would be cool, but I may not get to look at this for a few weeks. At first glance, /proxy/14500/ != //proxy/14500, so something may be amiss with slash parsing or requesting.

**Comment by BerserkerTroll** [comment]
> I think supporting Xpra would be cool

I think now it is not about supporting Xpra, it feels like a general WebSocket proxying issue.

> At first glance, /proxy/14500/ != //proxy/14500, so something may be amiss with slash parsing or requesting.

Indeed, it helped. A bit. Now it is able to connect to WebSocket (The message "Opening WebSocket connection" changed to "WebSocket connection established"), but it newer shows xterm and after 10-15 seconds throws me to `/connect.html` again.
And I see a stack trace:
```
[I 07:38:08.021 NotebookApp] Client sent subprotocols: ['binary']
[I 07:38:08.023 NotebookApp] Trying to establish websocket connection to ws://127.0.0.1:14500/
[I 07:38:08.282 NotebookApp] Websocket connection established to ws://127.0.0.1:14500/
[E 07:38:13.566 NotebookApp] Uncaught exception in /proxy/14500/
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/site-packages/tornado/websocket.py", line 801, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/usr/lib64/python3.6/site-packages/tornado/websocket.py", line 780, in _write_frame
        return self.stream.write(frame)
      File "/usr/lib64/python3.6/site-packages/tornado/iostream.py", line 525, in write
        self._check_closed()
      File "/usr/lib64/python3.6/site-packages/tornado/iostream.py", line 1058, in _check_closed
        raise StreamClosedError(real_error=self.error)
    tornado.iostream.StreamClosedError: Stream is closed
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/site-packages/tornado/websocket.py", line 498, in _run_callback
        result = callback(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 162, in on_message
        self.ws.write_message(message)
      File "/usr/lib64/python3.6/site-packages/tornado/websocket.py", line 1176, in write_message
        return self.protocol.write_message(message, binary=binary)
      File "/usr/lib64/python3.6/site-packages/tornado/websocket.py", line 803, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
```
Errors from Xpra (just in case):
```
2018-05-31 08:06:43,769 unknown or invalid packet type: suspend from Protocol(ws websocket: 127.0.0.1:14500 <- 127.0.0.1:42432)
2018-05-31 08:06:55,532 unknown or invalid packet type: resume from Protocol(ws websocket: 127.0.0.1:14500 <- 127.0.0.1:42448)
2018-05-31 08:06:59,484 unknown or invalid packet type: resume from Protocol(ws websocket: 127.0.0.1:14500 <- 127.0.0.1:42464)
2018-05-31 08:07:13,013 unknown or invalid packet type: sound-control from Protocol(ws websocket: 127.0.0.1:14500 <- 127.0.0.1:42480)
```

Ofc, I do not see these errors and the stack trace when I connect directly to localhost:14500.

**Comment by BerserkerTroll** [comment]
I've debugged it in Wireshark a bit. I've spotted very strange things. The proxy answers to Upgrade request **immediately** with HTTP 101 "Switching protocol", before it even sends the request to the backend! Probably I'm bad at asynchronous programming, but it looks too asynchronous for me.

In details, when I connect directly, HTML5 client switches protocol to websocket and sends "hello" packet to the Xpra server:

1. Browser -> Server: Upgrade to WebSocket
2. Server -> Browser:  HTTP 101 Switching protocol
3. Browser -> Server: WebSocket: Hello message with client details
4. Server -> Browser: answer to the hello, communication starts

Behind the proxy, the "hello" message never gets to the backend:

1. Browser -> Proxy: Upgrade to WebSocket
2. Proxy -> Browser: HTTP 101 Switching protocol — haven't even asked the backend!!!
3. Proxy -> Backend: Upgrade to WebSocket
4. Browser -> Proxy: WebSocket: Hello message with client details — Proxy sends it to /dev/null
5. Backend -> Proxy: HTTP 101 Switching protocol
6. (10 seconds later) Browser -> Proxy: WebSocket connection close — never got answer to Hello request
7. Proxy -> Backend: WebSocket connection close — at lest "connection close" was not redirected to /dev/null, thanks!

**Comment by BerserkerTroll** [comment]
Well, I've added 1 second delay before "hello" request is sent and now the HTML5 client is able to connect and show me the xterm window. Although not everything working as expected: without window manager running, the HTML5 client draws window frames itself and loads png-images of close and minimize buttons from the server. However, these images can't be loaded through the proxy.

I think the WebSocket proxying logics is flawed: the https://stackoverflow.com/questions/38663666/how-can-i-serve-a-http-page-and-a-websocket-on-the-same-url-in-tornado method is not intended for proxies. The proxy is answering immediately to the Upgrade request whilst it shall respond with the backend response.

**Comment by BerserkerTroll** [comment]
I don't know how stupid is this asyncprogrammingwise, because I don't know much about Python and Tornado.
It is just works for me:
```diff
--- a/nbserverproxy/handlers.py
+++ b/nbserverproxy/handlers.py
@@ -93,12 +93,11 @@ class WebSocketHandlerMixin(websocket.WebSocketHandler):
     async def get(self, *args, **kwargs):
         if self.request.headers.get("Upgrade", "").lower() != 'websocket':
             return await self.http_get(*args, **kwargs)
-        # super get is not async
-        super().get(*args, **kwargs)
+        return await self.ws_get(*args, **kwargs)
 
 
 class LocalProxyHandler(WebSocketHandlerMixin, IPythonHandler):
-    async def open(self, port, proxied_path=''):
+    async def ws_get(self, port, proxied_path=''):
         """
         Called when a client opens a websocket connection.
 
@@ -148,8 +147,9 @@ class LocalProxyHandler(WebSocketHandlerMixin, IPythonHandler):
                 on_message_callback=message_cb, on_ping_callback=ping_cb)
             self._record_activity()
             self.log.info('Websocket connection established to {}'.format(client_uri))
+            super(WebSocketHandlerMixin, self).get(port, proxied_path)
 
-        ioloop.IOLoop.current().add_callback(start_websocket_connection)
+        return await start_websocket_connection()
 
     def on_message(self, message):
         """
```
