### ISSUE TITLE
Does it work with Tensorboard?

### ISSUE THREAD

**Issue by hadim** [jupyterhub/nbserverproxy#41]
The plugin does not seem to work with [Tensorboard](https://www.tensorflow.org/programmers_guide/summaries_and_tensorboard).

![screenshot from 2018-06-30 22-31-27](https://user-images.githubusercontent.com/528003/42130509-592b6db0-7cb5-11e8-8a3b-60a7d31c2ff2.png)

Can you confirm ?

**Comment by betatim** [comment]
Do you have a repo that is setup with TensorBoard and works on mybinder.org? That would make it easier to debug.

**Comment by hadim** [comment]
The PR does not fix it.

- Launch https://mybinder.org/v2/gh/hadim/binder-test/master?urlpath=lab
- Open a terminal.
- Execute `tensorboard --logdir` .
- Navigate to the proxy by adding `proxy/6006` to the URL.

On binder, I got a 404 error. Bu locally the Tensorboard UI load and then stop (probably because of some 404 errors, see the screenshots for details).

**Comment by hadim** [comment]
My bad I forgot the enable the extension.

I tried to add the `postBuild` file but the extension does not seem to load... I must be missing something obvious: https://github.com/hadim/binder-test/blob/master/postBuid

**Comment by hadim** [comment]
My bad again `postBuild` filename was misspelt... I can now reproduce the issue: https://mybinder.org/v2/gh/hadim/binder-test/master?urlpath=lab

**Comment by betatim** [comment]
If I launch your binder and then visit https://hub.mybinder.org/user/hadim-binder-test-<UNIQUENUMBERHERE>/proxy/6006 I see the output of tensorboard. I think this means it works?

Should we close this issue?

**Comment by hadim** [comment]
Yes, Tensoboard interface shows up but if you open your browser console, you'll see a lot of 404 errors. I think Tensorboard is using WebSocket and something else to communicate with the server and retrieve info.

To better illustrate the issue  have added a notebook to the repo called `TF_Example.ipynb`: https://mybinder.org/v2/gh/hadim/binder-test/master?urlpath=lab

If you execute the notebook and then launch `tensorboard --logdir=/tmp/tensorflow_logs ` in a terminal when you visit https://hub.mybinder.org/user/hadim-binder-test-/proxy/6006, you should see a message `Failed to load the set of active dashboards.`

Without the proxy and locally I see TF scalar values and the TF graph:

![screenshot from 2018-07-01 16-39-52](https://user-images.githubusercontent.com/528003/42138574-787a9586-7d4d-11e8-9223-d5cae190fbef.png)

![screenshot from 2018-07-01 16-40-01](https://user-images.githubusercontent.com/528003/42138575-7cb4d288-7d4d-11e8-8930-1b728a731aae.png)

**Comment by betatim** [comment]
Thanks for the instructions. When I run it and look at the network requests being made I see lots of requests to `https://hub.mybinder.org/user/hadim-binder-test-UNIQUE/proxy/data/runs` which result in 404 errors. Not sure why tensor board cuts off the port number. Maybe it has a baseUrl configuration option or something like that?

If you manually try out `https://hub.mybinder.org/user/hadim-binder-test-UNIQUE/proxy/6006/data/runs` (with port) you get a JSON response. So I think this is something about configuring tensorboard.

**Comment by hadim** [comment]
Thank you @betatim. I think you got the cause of the issue correctly. Unfortunately after trying a bunch of `--path_prefix`, `--base_url` and `--host` options, I can't get it to work.

I'll open an issue on the TB repo.

Thanks for the help.

**Comment by hadim** [comment]
Easy fix: add a trailing slash at the end of the URL.

**Comment by betatim** [comment]
"Easy" :) Only took two people several hours to work out :-/

Thanks for making the examples for reproducing this and for figuring it out in the end!

I updated the title to try and make it so others with similar problems will find it, not just tensorboard users.
