### ISSUE TITLE
Setting up issue

### ISSUE THREAD

**Issue by raybellwaves** [jupyterhub/nbserverproxy#45]
Hi,

I'm relatively new to proxy servers so I apologize for my ignorance on the subject and ignorance on using this package.

I came to `nbserverproxy` via the [`dask-jobqueue`](https://github.com/dask/dask-jobqueue) project. I am hoping to tunnel my notebook from the HPC to my local machine (laptop) and also tunnel the [`dask dashboard` ](http://dask.pydata.org/en/latest/diagnostics-distributed.html#dashboard) which is typically served  at http://localhost:8787/status. I'm having trouble accessing the dashboard and `nbserverproxy` was proposed as a solution. Unfortunately, I couldn't get `nbserverproxy` to work and I was wondering if I was doing something wrong in the setup?

The original issue is posted at https://github.com/dask/dask-jobqueue/issues/116 but I realized I should probably ask here for help with `nbserverproxy` rather than the guys in `dask-jobqueue`.

I have an example below where I am trying to get the [README example](https://github.com/jupyterhub/nbserverproxy#example) to work

```
(djq_lsf) [rxb826@pegasus ~]$ conda install -c conda-forge nbserverproxy
(djq_lsf) [rxb826@pegasus ~]$ jupyter serverextension enable --py nbserverproxy
Enabling: nbserverproxy
- Writing config: /nethome/rxb826/.jupyter
    - Validating...
      nbserverproxy  OK
(djq_lsf) [rxb826@pegasus ~]$ jupyter lab --no-browser
[I 00:13:06.932 LabApp] The Jupyter Notebook is running at:
[I 00:13:06.932 LabApp] http://localhost:8888/?token=...
```
Open http://localhost:8888 on my laptop and try the [README example](https://github.com/jupyterhub/nbserverproxy#example)
<img width="769" alt="screen shot 2018-08-04 at 12 21 12 am" src="https://user-images.githubusercontent.com/17162724/43672461-5bb26b4c-977c-11e8-916f-ea021b5dbc4c.png">

<img width="291" alt="screen shot 2018-08-04 at 12 21 47 am" src="https://user-images.githubusercontent.com/17162724/43672464-6ecf16da-977c-11e8-8259-8343fc63a248.png">

<img width="542" alt="screen shot 2018-08-04 at 12 23 10 am" src="https://user-images.githubusercontent.com/17162724/43672485-bff96e70-977c-11e8-818c-bc101051f463.png">

**Comment by betatim** [comment]
You posted a lot of details but didn't explicitly mention that you started the python webserver example as mentioned in the README. If you do that do you still get the error message when connecting to the proxy?
