### ISSUE TITLE
Binary websockets currently not working (easy fix)

### ISSUE THREAD

**Issue by adsche** [jupyterhub/nbserverproxy#50]
Hi,

first of all, thanks for the great project, I was halfway through implementing something similar myself when I found it.

I'm using it to proxy a VNC connection (like nbnovnc) which uses a binary websocket. I found that connection could be established but traffic would stop after the RFB handshake (which just states the protocol version in all ASCII characters).

Turns out, binary messages from the backend are not relayed properly to the frontend. The reason is https://github.com/jupyterhub/nbserverproxy/blob/master/nbserverproxy/handlers.py#L163

Similar to when proxying from frontend to backend, it should instead be:

    self.ws.write_message(message, binary=type(message) is bytes)

With that, e.g., nbnovnc runs perfectly again.

Cheers!

**Comment by betatim** [comment]
Thanks for the debugging!

Do you want to make a PR that implements this?

I'd suggest we change `type(message) is bytes` to `isinstance(message, bytes)` which is the Python way of checking if something is an instance of a particular type in both cases.
