### ISSUE TITLE
main.js not found 404 error

### ISSUE THREAD

**Issue by IamViditAgarwal** [jupyterhub/nbserverproxy#53]
Hi , I have followed all the steps mentioned in installing this server extension , But when I am launching this , I am getting 404 error of 
`require.min.js:1 GET http://localhost:8888/main.js net::ERR_ABORTED 404 (Not Found)
req.load @ require.min.js:1
load @ require.min.js:1
load @ require.min.js:1
fetch @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
enable @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
each @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
(anonymous) @ require.min.js:1
setTimeout (async)
req.nextTick @ require.min.js:1
o @ require.min.js:1
configure @ require.min.js:1
requirejs @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
require.min.js:1 Uncaught Error: Script error for "main"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:1)
    at HTMLScriptElement.onScriptError (require.min.js:1)`

Can anyone help me to resolve this issue . 
I have a file that is running on port 8866. I am trying to open it in the way that is decribed in the README.md file but getting this error again and again..

PS : I checked the source code . In the file https://github.com/jupyterhub/nbserverproxy/blob/master/nbserverproxy/__init__.py , in function `_jupyter_nbextension_paths()` from where it is requiring `nbserverproxy/main` .. I guess this line of code is giving me error of main.js not found . ? 

Thanks in advance
Vidit

**Comment by ryanlovett** [comment]
Hi @IamViditAgarwal , is this fixed by https://github.com/jupyterhub/jupyterhub/issues/2292#issuecomment-436909819 ?

**Comment by IamViditAgarwal** [comment]
> Hi @IamViditAgarwal , is this fixed by [jupyterhub/jupyterhub#2292 (comment)](https://github.com/jupyterhub/jupyterhub/issues/2292#issuecomment-436909819) ?

Hi , actually that was an older issue and it is different from this . 
Issue : I am getting main.js file not found . 
My process which is running on port 8866 (for which I am using nbserverproxy) has code folder structure like this : 

├── dist
│   ├── 0.libwidgets.js
│   ├── 0.libwidgets.js.map
│   ├── 1.libwidgets.js
│   ├── 1.libwidgets.js.map
│   ├── 674f50d287a8c48dc19ba404d20fe713.eot
│   ├── 912ec66d7572ff821749319396470bde.svg
│   ├── af7ae505a9eed503f8b8e6982036873e.woff2
│   ├── b06871f281fee6b241d60582ae9369b9.ttf
│   ├── fee66e712a8a08eef5805a46892932ad.woff
│   ├── @jupyter-widgets
│   │   ├── base.js
│   │   └── controls.js
│   ├── libwidgets.js
│   └── libwidgets.js.map
├── index.html
└── main.js

Now when I proxy this service to ` /proxy/8866 ` (using nbserverproxy), the code is unable to get ` main.js and libwidget.js ` which is in `/dist` folder and this gave me 404 error. 
Could you help me , how can I get the path to those files ?
PS: Thanks in advance
Vidit

**Comment by ryanlovett** [comment]
Can you try adding a slash to your url? e.g. /proxy/8866/

Otherwise can you describe the app you're proxying?

**Comment by IamViditAgarwal** [comment]
> Can you try adding a slash to your url? e.g. /proxy/8866/
> 
> Otherwise can you describe the app you're proxying?

I have tried with / but not working.
I have a doubt :As this nbserverproxy is running inside a docker container. So for proxying any arbitary service , do I have to run that service after container is in running state by runnint it from terminal ?

**Comment by ryanlovett** [comment]
The service needs to be running in the same network namespace as your notebook. If your notebook is running in a container then your service should be running in it too.

If the proxy can't talk to the service, it won't work. Some extensions that subclass this one manage the process that they proxy (nbrsessionproxy, nbstencilaproxy) via SuperviseAndProxyHandler. You could run some process manager inside your container like tini or supervisord, or you can manually start the service in a jupyter terminal.

**Comment by IamViditAgarwal** [comment]
> The service needs to be running in the same network namespace as your notebook. If your notebook is running in a container then your service should be running in it too.
> 
> If the proxy can't talk to the service, it won't work. Some extensions that subclass this one manage the process that they proxy (nbrsessionproxy, nbstencilaproxy) via SuperviseAndProxyHandler. You could run some process manager inside your container like tini or supervisord, or you can manually start the service in a jupyter terminal.

My service is running in same container in which Jupyter Notebook is running, I will try with the process managers .. Thanks

**Comment by IamViditAgarwal** [comment]
HI , I figured out this , I think this is the issue of the absolute urls something. Like my service is running on port 8866 , so the url would be like `https://jupyterhub.domain.com/user/{some user}/proxy/8866/` . <br/> I need to enter a ending `/` there at last.

Thanks
Closing this issue
